# Generated by Django 3.2.7 on 2021-09-12 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_name', models.CharField(max_length=500)),
                ('date_time', models.CharField(max_length=500)),
                ('current_stage', models.CharField(max_length=500)),
                ('launch_status', models.CharField(max_length=500)),
                ('launch_provider', models.CharField(max_length=500)),
                ('rocket_config', models.CharField(max_length=500)),
                ('payload_name', models.CharField(max_length=500)),
                ('payload_mission', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('reliable', models.BooleanField()),
                ('unreliable', models.BooleanField()),
                ('official', models.BooleanField()),
                ('false', models.BooleanField()),
                ('launch_status', models.BooleanField()),
                ('time_change', models.BooleanField()),
                ('general_announcements', models.BooleanField()),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='launches.launch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upates_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
