# Generated by Django 3.2.7 on 2021-09-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0002_launch_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launch_status',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='launch',
            name='payload_mission',
            field=models.CharField(max_length=2000),
        ),
    ]
