# Generated by Django 3.2.7 on 2021-09-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0006_auto_20210913_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='general_announcements',
        ),
        migrations.AddField(
            model_name='update',
            name='general_announcements',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='update',
            name='launch_status',
        ),
        migrations.AddField(
            model_name='update',
            name='launch_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='update',
            name='time_change',
        ),
        migrations.AddField(
            model_name='update',
            name='time_change',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
