# Generated by Django 3.2.7 on 2021-09-14 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('launches', '0007_auto_20210914_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
